use failure::Error;
use rime::server::line_server::run;

fn main() -> Result<(), Error> {
    run()
}
